FROM node:12 AS build-env

WORKDIR /usr/src/app
COPY ./package.json ./
# COPY ./package-lock.json ./
RUN npm install
COPY ./lerna.json ./
COPY ./client/ ./client/
COPY ./common/ ./common/
RUN npm run bootstrap -- --scope=@akrons/test --include-dependencies
RUN npm run build -- --scope=@akrons/test --include-dependencies

# Build runtime image
FROM nginx:latest
COPY --from=build-env /usr/src/app/client/test/dist/test /usr/share/nginx/html
COPY ./client/nginx.conf /etc/nginx/nginx.conf
