export const AUTH_ENDPOINT_PROVIDER = 'AUTH_HOST_PROVIDER';
export const AUTH_LOGIN_REDIRECT_PROVIDER = 'AUTH_LOGIN_REDIRECT_PROVIDER';
export const AUTH_LOGIN_ROUTE_PROVIDER = 'AUTH_LOGIN_ROUTE_PROVIDER';
export const AUTH_CHANGE_PASSWORD_ROUTE_PROVIDER = 'AUTH_CHANGE_PASSWORD_ROUTE_PROVIDER';
export const AUTH_CHANGE_PASSWORD_REDIRECT_PROVIDER = 'AUTH_CHANGE_PASSWORD_REDIRECT_PROVIDER';
