export const CORE_PRODUCTION_INJECTOR = 'CORE_PRODUCTION_INJECTOR';
export const CORE_TITLE_INJECTOR = 'CORE_TITLE_INJECTOR';
export const CORE_MOBILE_BREAKPOINT_PX_INJECTOR = 'CORE_MOBILE_BREAKPOINT_PX_INJECTOR';
